Repository imhardikdesai/Currency-Converter, pull requests merged in 2023-10, with the labels that each got.

#5 Create About Page
  src/App.js
  src/components/About/About.jsx
  src/components/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 [DONE] | Add enhance Readme.md file #6
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#8 [FIX] | #7
  public/_redirects
Labels: bug, hacktoberfest, hacktoberfest-accepted

#11 refactored dark theme
  src/components/About/About.jsx
  src/components/Form/form.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#18 Add dynamic year copyright in the footer
  src/components/Footer/Footer.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#20 fixed exchange rate and add symbol
  src/components/CTA/CTA.jsx
  src/components/Form/Form.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#22 [FEATURE] Live conversion
  src/components/Form/Form.jsx
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#21 [STYLING] Fixed Styling inconsistencies in the form
  src/components/Form/Form.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
